#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'ohai'
cookbook 'apt'
cookbook 'hostname'
cookbook 'git'
cookbook 'rbenv'
cookbook 'user'
cookbook 'sudo'
cookbook 'nginx'
cookbook 'database'
cookbook 'postgresql'
cookbook 'postfix'
