include_recipe 'application::base'
include_recipe 'application::ruby'
include_recipe 'application::user'
include_recipe 'application::folders'
include_recipe 'application::nginx'
include_recipe 'application::unicorn'
include_recipe 'application::database'
