maintainer       'Max Prokopiev'
maintainer_email 'me@maxprokopiev.com'
license          'MIT'
description      'Installs/Configures Rails application'
long_description 'Installs/Configures Rails application'
version          '0.0.1'

depends 'ohai'
depends 'apt'
depends 'hostname'
depends 'git'
depends 'rbenv'
depends 'user'
depends 'sudo'
depends 'nginx'
depends 'database'
depends 'postgresql'
depends 'postfix'
